
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gu.language;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int puntoYComa = 31;
  public static final int resTitulo = 13;
  public static final int resGrosor = 21;
  public static final int llaveAbierta = 23;
  public static final int resEjeY = 15;
  public static final int resEjeX = 14;
  public static final int signoMas = 35;
  public static final int valorCadena = 3;
  public static final int dosPuntos = 32;
  public static final int resDefinirXYLine = 10;
  public static final int signoDividido = 38;
  public static final int signoIgual = 34;
  public static final int coma = 33;
  public static final int signoPor = 37;
  public static final int resDefinirGlobales = 7;
  public static final int interrogAbierto = 29;
  public static final int identificador = 4;
  public static final int resPuntos = 22;
  public static final int parentCerrado = 26;
  public static final int corcheteCerrado = 28;
  public static final int resGaleria = 11;
  public static final int resID = 12;
  public static final int signoMenos = 36;
  public static final int EOF = 0;
  public static final int resString = 5;
  public static final int error = 1;
  public static final int llaveCerrada = 24;
  public static final int parentAbierto = 25;
  public static final int valorEntero = 2;
  public static final int resTituloY = 18;
  public static final int resGraficaLineas = 9;
  public static final int corcheteAbierto = 27;
  public static final int resTituloX = 17;
  public static final int resNombre = 19;
  public static final int resColor = 20;
  public static final int resInt = 6;
  public static final int interrogCerrado = 30;
  public static final int resGraficaBarras = 8;
  public static final int resPuntosXY = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "valorEntero",
  "valorCadena",
  "identificador",
  "resString",
  "resInt",
  "resDefinirGlobales",
  "resGraficaBarras",
  "resGraficaLineas",
  "resDefinirXYLine",
  "resGaleria",
  "resID",
  "resTitulo",
  "resEjeX",
  "resEjeY",
  "resPuntosXY",
  "resTituloX",
  "resTituloY",
  "resNombre",
  "resColor",
  "resGrosor",
  "resPuntos",
  "llaveAbierta",
  "llaveCerrada",
  "parentAbierto",
  "parentCerrado",
  "corcheteAbierto",
  "corcheteCerrado",
  "interrogAbierto",
  "interrogCerrado",
  "puntoYComa",
  "dosPuntos",
  "coma",
  "signoIgual",
  "signoMas",
  "signoMenos",
  "signoPor",
  "signoDividido"
  };
}

